import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "on-primary-container": "#eeefff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5c647a",
        "primary-container": "#2563eb",
        "inverse-surface": "#213145",
        "tertiary-container": "#bc4800",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "inverse-on-surface": "#eaf1ff",
        background: "#f8f9ff",
        "on-tertiary-fixed": "#360f00",
        "on-primary-fixed-variant": "#003ea8",
        surface: "#f8f9ff",
        secondary: "#565e74",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#131b2e",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#ffb596",
        "on-primary-fixed": "#00174b",
        primary: "#004ac6",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        outline: "#737686",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed-variant": "#7d2d00",
        "inverse-primary": "#b4c5ff",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#dae2fd",
        "on-secondary-fixed-variant": "#3f465c",
        "secondary-fixed": "#dae2fd",
        "surface-tint": "#0053db",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#ffdbcd",
        "surface-container": "#e5eeff",
        tertiary: "#943700",
        "surface-container-highest": "#d3e4fe",
        success: "#22c55e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        unit: "4px",
        "container-margin": "32px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)"],
        "display-lg": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
        "title-lg": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "title-md": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "title-md": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
