name: Deploy to AWS EC2

on:
  workflow_run:
    workflows:
      - "Run Tests"
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EC2

    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'testing-branch' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify Secrets
        run: |
          test -n "${{ secrets.EC2_HOST }}" || (echo "EC2_HOST missing" && exit 1)
          test -n "${{ secrets.EC2_SSH_KEY }}" || (echo "EC2_SSH_KEY missing" && exit 1)
          echo "All required secrets are available."

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            cd /home/ubuntu/ProcureFlow-AI

            echo "Updating repository..."
            git reset --hard
            git checkout testing-branch
            echo "Pulling latest code..."
            git fetch origin
            git pull origin testing-branch

            echo "Activating virtual environment..."
            source .venv/bin/activate

            echo "Upgrading pip..."
            pip install --upgrade pip

            echo "Installing dependencies..."
            uv pip install -r backend/requirements.txt
            cd backend
            rm invoice_po.db 
            python3 -m app.database.init_db
            echo "Restarting service..."
            sudo systemctl daemon-reload
            sudo systemctl restart backend

            echo "Checking service status..."
            sudo systemctl status backend 

            echo "Deployment completed successfully."